Sniffer:
  include:
    file_type:
        rb:
          parser:
            - rb_parser
        js:
          parser:
            - js_parser
        erb:
          parser:
             - rb_parser
             - js_parser



